DROP TABLE PRODUTO;

CREATE TABLE PRODUTO (
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	DESCRICAO VARCHAR(255),
	VALOR NUMERIC(16,2),
	SKU VARCHAR(20)
);

DROP TABLE CLIENTE;

CREATE TABLE CLIENTE (
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	DATA_CADASTRO DATE,
	NASCIMENTO DATE NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	ENDERECO VARCHAR(255) NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	TELEFONE VARCHAR (14),
	EMAIL VARCHAR(255)
);